[[pages]]
path = "sections/nodes_workflow.py"
name = "Nodes Workflow"
icon = ":test_tube:"

[[pages]]
path = "sections/dataframe_analysis.py"
name = "Dataframe Analysis"
icon = ":bar_chart:"

[[pages]]
path = "sections/plots.py"
name = "Plots"
icon = ":frame_with_picture:"

[[pages]]
path = "sections/python_editor.py"
name = "Python Editor"
icon = ":memo:"